from contextlib import closing

from db import get_connection

# Campus organizations, ordered alphabetically as published.
# Categories are inferred from each organization's name; description and
# meeting_info are left NULL until real data is collected for them.
ORGS = [
    ("A Dog's Way Home", "Service/Philanthropy"),
    ("Adventist Christian Fellowship", "Religious/Spiritual"),
    ("African Students Organization", "Cultural/International"),
    ("Ag Eco Competitive Club", "Agriculture"),
    ("Agricultural Communicators of Tomorrow", "Agriculture"),
    ("Agricultural Economics Grad Student Association", "Graduate Student Organization"),
    ("Agricultural Education and Communications Graduate Organization", "Graduate Student Organization"),
    ("Agricultural Educators of Tomorrow", "Agriculture"),
    ("Agricultural Law Association", "Law/Pre-Law"),
    ("Agronomy Club", "Agriculture"),
    ("AjedRaiders", "Special Interest"),
    ("Alpha Lambda Delta & PES", "Academic/Honor Society"),
    ("Alpha Psi Omega", "Arts/Performance"),
    ("Alpha Zeta", "Academic/Honor Society"),
    ("Ambassadors for Agriculture", "Agriculture"),
    ("American Association Of Drilling Engineers", "Engineering/Professional"),
    ("American Association of Family & Consumer Sciences-Family, Career and Community Leaders of America", "Academic/Departmental"),
    ("American Association of Petroleum Geologists Student Chapter", "Science/Research"),
    ("American Chemical Society-Student Affiliate", "Science/Research"),
    ("American Institute of Chemical Engineers", "Engineering/Professional"),
    ("American Institute of Graphic Arts", "Arts/Design"),
    ("American Medical Student Association Tech Chapter", "Health/Pre-Professional"),
    ("American Medical Women's Association", "Health/Pre-Professional"),
    ("American Rock Mechanics Association", "Engineering/Professional"),
    ("American Society of Civil Engineers", "Engineering/Professional"),
    ("American Society of Interior Designers", "Arts/Design"),
    ("American Society of Mechanical Engineers", "Engineering/Professional"),
    ("American String Teachers Association", "Arts/Performance"),
    ("Anchor Student Club", "Religious/Spiritual"),
    ("Animal and Food Science Academic Quadrathlon", "Agriculture"),
    ("Arnold Air Society Spencer Brian LaBrie Squadron", "Military/ROTC"),
    ("Asian Pacific American Law Student Association", "Law/Pre-Law"),
    ("Associated General Contractors", "Engineering/Professional"),
    ("Association for Competitive Math Olympics", "Academic/Departmental"),
    ("Association For Computing Machinery", "Technology/Computing"),
    ("Association of Bangladeshi Students and Scholars", "Cultural/International"),
    ("Association of Biologists", "Science/Research"),
    ("Association of Competitive Engineers", "Engineering/Competition"),
    ("Association of Information Technology Professionals", "Technology/Computing"),
    ("Association of Students Acting in Service", "Service/Philanthropy"),
    ("Atlas Campus Fellowship", "Religious/Spiritual"),
    ("Ballroom Dance at Tech", "Arts/Performance"),
    ("Baptist Student Ministry", "Religious/Spiritual"),
    ("Best Buddies", "Service/Philanthropy"),
    ("Beta Beta Beta- Nu Alpha Chapter", "Academic/Honor Society"),
    ("Beta Gamma Sigma", "Academic/Honor Society"),
    ("Beyond Barriers - Inclusive Learning Advocates for Accessible Education", "Advocacy/Inclusion"),
    ("Biotechnology Organization for Student Success", "Science/Research"),
    ("Black Arts Society", "Cultural/International"),
    ("Black Business Student Association", "Business/Professional"),
    ("Black Graduate Student Association", "Graduate Student Organization"),
    ("Black Graduation Alliance", "Cultural/International"),
    ("Black Law Students Association", "Law/Pre-Law"),
    ("Black Student Association", "Cultural/International"),
    ("Block & Bridle", "Agriculture"),
    ("Blue Book Initiative", "Service/Philanthropy"),
    ("Board Of Barristers", "Law/Pre-Law"),
    ("Bookmarked Book Club", "Special Interest"),
    ("Campus Crusade for Christ", "Religious/Spiritual"),
    ("Cancer Advocacy and Research in Biological Sciences", "Science/Research"),
    ("Canterbury Episcopal Campus Ministry", "Religious/Spiritual"),
    ("Caribbean Student Association", "Cultural/International"),
    ("Catholic Student Association", "Religious/Spiritual"),
    ("CHAARG", "Sports/Recreation"),
    ("Chabad Jewish Student Group", "Religious/Spiritual"),
    ("Chemical Engineering Graduate Student Association", "Graduate Student Organization"),
    ("Chemistry Graduate Student Organization", "Graduate Student Organization"),
    ("Chi Alpha Christian Fellowship", "Religious/Spiritual"),
    ("Chi Epsilon", "Academic/Honor Society"),
    ("Chi Sigma Iota", "Academic/Honor Society"),
    ("Children's Health and Medical Program", "Health/Pre-Professional"),
    ("Christian Legal Society", "Religious/Spiritual"),
    ("Christian Veterinary Fellowship", "Religious/Spiritual"),
    ("Christians At Tech", "Religious/Spiritual"),
    ("CISER Scholar Service Organization", "Service/Philanthropy"),
    ("Clay Club", "Arts/Design"),
    ("Clinical Psychology Graduate Student Council", "Graduate Student Organization"),
    ("Coalition of Healthcare Students", "Health/Pre-Professional"),
    ("Coalition/Councils", "Student Government/Leadership"),
    ("Codename: Raider", "Special Interest"),
    ("CodePath.org", "Technology/Computing"),
    ("Collective Action", "Political/Advocacy"),
    ("College of Arts & Sciences Student Ambassadors", "Student Government/Leadership"),
    ("College of Health and Human Sciences Ambassadors", "Student Government/Leadership"),
    ("College of Health and Human Sciences Society of Future Clinicians", "Health/Pre-Professional"),
    ("College of Human Sciences Dean's Leadership Council (DLC)", "Student Government/Leadership"),
    ("College of Media & Communication Graduate Student Society", "Graduate Student Organization"),
    ("Collegiate Cattlemen's Association", "Agriculture"),
    ("ColorStack", "Technology/Computing"),
    ("Communication Studies Society", "Media/Communication"),
    ("Counseling Council", "Academic/Departmental"),
    ("Criminal Law Association", "Law/Pre-Law"),
    ("Criminology Club", "Academic/Departmental"),
    ("Cyber Raiders", "Technology/Computing"),
    ("Céfiro: Enlace Hispano, Cultural y Literario", "Cultural/International"),
    ("Daily Toreador", "Media/Communication"),
    ("Dancers with Soul: Hip Hop Dance Team", "Arts/Performance"),
    ("Delight Ministries", "Religious/Spiritual"),
    ("Democrats for Texas", "Political/Advocacy"),
    ("Dirty Techsans", "Special Interest"),
    ("Double T Locksport", "Special Interest"),
    ("Dr. Bernard Harris Pre-Medical Society", "Health/Pre-Professional"),
    ("Education Graduate Student Organization", "Graduate Student Organization"),
    ("El Club de Español", "Cultural/International"),
    ("Empire A Cappella", "Arts/Performance"),
    ("Energy Law Interest Group", "Law/Pre-Law"),
    ("Engineering Diplomats", "Student Government/Leadership"),
    ("Environmental Law Society", "Law/Pre-Law"),
    ("Environmental Toxicology Student Association", "Science/Research"),
    ("Estate Planning And Community Property Law Journal", "Law/Pre-Law"),
    ("Eta Omicron Nu", "Academic/Honor Society"),
    ("Family Business Student Organization", "Business/Professional"),
    ("Family Law Society", "Law/Pre-Law"),
    ("Fashion and Media Entertainment", "Arts/Design"),
    ("Filipino Student Association", "Cultural/International"),
    ("Finance Association", "Business/Professional"),
    ("First Lubbock College Ministry", "Religious/Spiritual"),
    ("Food Science Club", "Agriculture"),
    ("Forensic Science Society", "Science/Research"),
    ("Foundation Retreat", "Religious/Spiritual"),
    ("Friendly Raiders for Education Equity", "Service/Philanthropy"),
    ("Friends of Médecins Sans Frontières", "Service/Philanthropy"),
    ("Future Lawyers of Today", "Law/Pre-Law"),
    ("Geography & Youth Mappers", "Science/Research"),
    ("Geoscience Student Society", "Science/Research"),
    ("Ghana Students Association", "Cultural/International"),
    ("Goin' Band Student Association", "Arts/Performance"),
    ("Google Developer Student Club", "Technology/Computing"),
    ("Graduate Association of Physicists", "Graduate Student Organization"),
    ("Graduate English Society", "Graduate Student Organization"),
    ("Graduate Hospitality Management and Retail Association", "Graduate Student Organization"),
    ("Graduate Nutrition Organization", "Graduate Student Organization"),
    ("Hi-Tech Fashion Group", "Arts/Design"),
    ("High Riders", "Spirit/Traditions"),
    ("Higher Education Student Association", "Academic/Departmental"),
    ("Hillel", "Religious/Spiritual"),
    ("Hispanic Law Student Association", "Law/Pre-Law"),
    ("Hispanic Student Society", "Cultural/International"),
    ("Honors Association for Aspiring Pre-health Tracks", "Health/Pre-Professional"),
    ("Honors College Bayless Elementary Mentoring Program", "Service/Philanthropy"),
    ("Horticulture Society", "Agriculture"),
    ("HOSA Future Health Professionals", "Health/Pre-Professional"),
    ("Human Development and Family Sciences and Early Childhood Ambassadors", "Student Government/Leadership"),
    ("Human Development And Family Sciences Graduate Student Association", "Graduate Student Organization"),
    ("Human Factors And Ergonomics Society", "Engineering/Professional"),
    ("ICMA Student Chapter Lubbock", "Business/Professional"),
    ("IDEAL", "Special Interest"),
    ("IEEE Eta Kappa Nu", "Academic/Honor Society"),
    ("IEEE Nuclear & Plasma Sciences Society", "Engineering/Professional"),
    ("Immigration Law Association", "Law/Pre-Law"),
    ("INFORMS Student Chapter", "Engineering/Professional"),
    ("Institute of Electrical and Electronics Engineers", "Engineering/Professional"),
    ("Institute of Industrial and Systems Engineers", "Engineering/Professional"),
    ("Intellectual Property Student Association", "Law/Pre-Law"),
    ("International Association of Business Communicators Tech Student Chapter", "Media/Communication"),
    ("International Association of Drilling Contractors", "Engineering/Professional"),
    ("International Interior Design Association", "Arts/Design"),
    ("Investment Management Association", "Business/Professional"),
    ("Involvement Ambassadors", "Student Government/Leadership"),
    ("Iota Iota Iota", "Academic/Honor Society"),
    ("Iota Tau Alpha", "Academic/Honor Society"),
    ("Japanese Student Association", "Cultural/International"),
    ("JINXX!", "Arts/Performance"),
    ("Journal of Technology, Law, and Society", "Law/Pre-Law"),
    ("Journal of the Energy Law Practitioner", "Law/Pre-Law"),
    ("JoyCentric Organization", "Service/Philanthropy"),
    ("Kinesiology and Sport Management Ambassadors", "Student Government/Leadership"),
    ("Knight Raiders", "Special Interest"),
    ("Knights of Architecture", "Arts/Design"),
    ("Knowledge Empowering You", "Service/Philanthropy"),
    ("Korean Student Association", "Cultural/International"),
    ("Latino Medical Student Association Plus", "Health/Pre-Professional"),
    ("Latter-Day Saint Student Association", "Religious/Spiritual"),
    ("Live Oak College Ministry", "Religious/Spiritual"),
    ("Livestock Judging Team", "Agriculture"),
    ("Llano Estacado Student Chapter Of The Society Of Environmental Toxicology And Chemistry", "Science/Research"),
    ("Lubbock Rotaract Club", "Service/Philanthropy"),
    ("Lutheran Student Fellowship", "Religious/Spiritual"),
    ("Managing Leaders Association", "Business/Professional"),
    ("Mantra Meditation", "Religious/Spiritual"),
    ("Matador Collegiate Farm Bureau", "Agriculture"),
    ("Matador MMA", "Sports/Recreation"),
    ("Matador Powerlifting Team", "Sports/Recreation"),
    ("Meat Animal Evaluation Team", "Agriculture"),
    ("Meat Judging Team", "Agriculture"),
    ("Meat Science Academic Quiz Bowl Team", "Agriculture"),
    ("Meat Science Association", "Agriculture"),
    ("Medical and Dental Global Brigades", "Service/Philanthropy"),
    ("Mediterranean Student Society", "Cultural/International"),
    ("MedLife", "Service/Philanthropy"),
    ("Metals Club", "Arts/Design"),
    ("MindMatters", "Health/Wellness"),
    ("Minorities in Agriculture, Natural Resources and Related Sciences", "Agriculture"),
    ("Minorities in Pre Law Alliance", "Law/Pre-Law"),
    ("Minority Association of Pre-Health Students", "Health/Pre-Professional"),
    ("Miracle Pennies College Edition", "Service/Philanthropy"),
    ("Missionary Baptist Student Fellowship", "Religious/Spiritual"),
    ("Model United Nations", "Academic/Departmental"),
    ("Mortar Board", "Academic/Honor Society"),
    ("Mu Epsilon Kappa Anime", "Special Interest"),
    ("Multicultural Pre-Dental Association", "Health/Pre-Professional"),
    ("Multicultural Student Business Association", "Business/Professional"),
    ("Museum Heritage Student Association", "Academic/Departmental"),
    ("Muslim Student Association", "Religious/Spiritual"),
    ("NAACP @ Tech", "Advocacy/Inclusion"),
    ("National Association of Teachers of Singing at Tech", "Arts/Performance"),
    ("National Marrow Donation Program", "Service/Philanthropy"),
    ("National Organization of Minority Architect Students Lubbock Chapter", "Arts/Design"),
    ("National Society of Black Engineers", "Engineering/Professional"),
    ("Navigators", "Religious/Spiritual"),
    ("Nepal Students Association", "Cultural/International"),
    ("Network of Enlightened Women", "Political/Advocacy"),
    ("Nigerian Students Association", "Cultural/International"),
    ("No Mind Left Behind", "Service/Philanthropy"),
    ("Non-Traditional Law Student Association", "Law/Pre-Law"),
    ("Organization Of Women Law Students", "Law/Pre-Law"),
    ("Orthodox Christian Fellowship", "Religious/Spiritual"),
    ("OUTlaw", "Law/Pre-Law"),
    ("Peers Against Tobacco", "Health/Wellness"),
    ("Personal Financial Planning Association", "Business/Professional"),
    ("Pets Are Worth Saving", "Service/Philanthropy"),
    ("Phi Alpha Theta: Zeta-Iota Chapter", "Academic/Honor Society"),
    ("Phi Upsilon Omicron", "Academic/Honor Society"),
    ("Philosophy Graduate Student Association", "Graduate Student Organization"),
    ("Physician Assistant Student Organization", "Health/Pre-Professional"),
    ("Pi Tau Sigma", "Academic/Honor Society"),
    ("Plant and Soil Science Graduate Council", "Graduate Student Organization"),
    ("Pre-Athletic Training Club", "Health/Pre-Professional"),
    ("Pre-Dental Society", "Health/Pre-Professional"),
    ("Pre-Nursing Association", "Health/Pre-Professional"),
    ("Pre-Optometry Professional Society", "Health/Pre-Professional"),
    ("Pre-Physical Therapy Club", "Health/Pre-Professional"),
    ("President's Select", "Student Government/Leadership"),
    ("Prosecution Law Association", "Law/Pre-Law"),
    ("Providing the Outside World with Empowerment and Resources", "Service/Philanthropy"),
    ("Psi Chi: International Honor Society In Psychology", "Academic/Honor Society"),
    ("Public Relations Student Society of America", "Media/Communication"),
    ("Raider Aerospace Society", "Engineering/Professional"),
    ("Raider Backpacking Club", "Sports/Recreation"),
    ("Raider Badminton Club", "Sports/Recreation"),
    ("Raider Bar Association", "Law/Pre-Law"),
    ("Raider Calisthenics Club", "Sports/Recreation"),
    ("Raider Entrepreneurship Club", "Business/Professional"),
    ("Raider Historical Fencing", "Sports/Recreation"),
    ("Raider Medical Screening Society", "Health/Pre-Professional"),
    ("Raider Power of Paranormal", "Special Interest"),
    ("Raider Precision Rifle Club", "Sports/Recreation"),
    ("Raider Recycling", "Service/Philanthropy"),
    ("Raider Red's Food Pantry", "Service/Philanthropy"),
    ("Raider Rhetoric Society", "Media/Communication"),
    ("Raider Riot", "Spirit/Traditions"),
    ("Raider Trumpet Guild", "Arts/Performance"),
    ("Raider's Knit & Knot", "Special Interest"),
    ("Raiders American Society of Microbiology Undergraduate Chapter", "Science/Research"),
    ("Raiders for Life", "Political/Advocacy"),
    ("Raiders for Reproductive Rights", "Political/Advocacy"),
    ("Raiders of The Law", "Law/Pre-Law"),
    ("Raiders Uncorked", "Special Interest"),
    ("Rawls Banking Association", "Business/Professional"),
    ("Rawls College of Business Dean's Student Council", "Student Government/Leadership"),
    ("Rawls Global Business Council", "Business/Professional"),
    ("Rawls Graduate Association", "Graduate Student Organization"),
    ("Real Estate Organization", "Business/Professional"),
    ("Red Costa Rica Female Futbol Club", "Sports/Recreation"),
    ("Red Costa Rica Men's Futbol Club", "Sports/Recreation"),
    ("Red Dirt Racing", "Engineering/Competition"),
    ("Red PlaNet", "Special Interest"),
    ("Red Raider Camp", "Spirit/Traditions"),
    ("Red Raider Racing", "Engineering/Competition"),
    ("Red Theatre Company", "Arts/Performance"),
    ("Redeemed Christian Church of God, Dominion Chapel Fellowship", "Religious/Spiritual"),
    ("Redeemer College Ministry", "Religious/Spiritual"),
    ("Reformed University Fellowship", "Religious/Spiritual"),
    ("Renewable Energy Student Association", "Engineering/Professional"),
    ("Robotics and Advanced Tech Society", "Engineering/Competition"),
    ("Sabre Flight Drill Team", "Military/ROTC"),
    ("Saddle Tramps", "Spirit/Traditions"),
    ("Sales Leadership Group", "Business/Professional"),
    ("School of Veterinary Medicine Companion Animal Club", "Veterinary"),
    ("School of Veterinary Medicine Graduate Student Association", "Veterinary"),
    ("Script Raiders", "Media/Communication"),
    ("Sigma Delta Pi", "Academic/Honor Society"),
    ("Sigma Tau Delta", "Academic/Honor Society"),
    ("Signing Raiders", "Advocacy/Inclusion"),
    ("Skyraiders", "Sports/Recreation"),
    ("Social Work Student Organization", "Academic/Departmental"),
    ("Society For Industrial And Applied Mathematics", "Academic/Departmental"),
    ("Society Of Environmental Professionals", "Science/Research"),
    ("Society of Hispanic Professional Engineers", "Engineering/Professional"),
    ("Society Of Petroleum Engineers", "Engineering/Professional"),
    ("Society of Plastics Engineers", "Engineering/Professional"),
    ("Society of Professional Journalists", "Media/Communication"),
    ("Society of Women Engineers", "Engineering/Professional"),
    ("South Asian Student Association", "Cultural/International"),
    ("Space Exploration Raiders", "Science/Research"),
    ("Special Olympics College", "Service/Philanthropy"),
    ("Sport Club Executive Council", "Sports/Recreation"),
    ("Sport Club Supervisors", "Sports/Recreation"),
    ("Sports and Entertainment Law Society", "Law/Pre-Law"),
    ("Sri Lankan Students Association", "Cultural/International"),
    ("Student Activities Board", "Student Government/Leadership"),
    ("Student Agricultural and Natural Resources Council", "Agriculture"),
    ("Student Alumni Board", "Student Government/Leadership"),
    ("Student Association for Fire Ecology", "Science/Research"),
    ("Student Association Of Marriage And Family Therapy", "Academic/Departmental"),
    ("Student Bar Association", "Law/Pre-Law"),
    ("Student Chapter of the American Association of Equine Practitioners", "Veterinary"),
    ("Student Chapter of the American Meteorological Society at Tech", "Science/Research"),
    ("Student Government Association", "Student Government/Leadership"),
    ("Student Mobilization", "Religious/Spiritual"),
    ("Student Nutrition Organization", "Health/Wellness"),
    ("Student Organ Donation Advocates", "Service/Philanthropy"),
    ("Student Union & Activities Community Outreach", "Service/Philanthropy"),
    ("Student Veterans of America", "Military/ROTC"),
    ("Student Veterinary Emergency Response Association", "Veterinary"),
    ("Student Veterinary Surgical Society", "Veterinary"),
    ("Students of East Africa at Tech", "Cultural/International"),
    ("Studio Hacks", "Arts/Design"),
    ("Tau Beta Pi", "Academic/Honor Society"),
    ("Teaching Techsans", "Academic/Departmental"),
    ("Tech Advertising Federation", "Media/Communication"),
    ("Tech American Society for Microbiology", "Science/Research"),
    ("Tech Archery Club", "Sports/Recreation"),
    ("Tech Astronomy Club", "Science/Research"),
    ("Tech Athletic Ambassadors", "Spirit/Traditions"),
    ("Tech Bass Fishing Team", "Sports/Recreation"),
    ("Tech Board Game Club", "Special Interest"),
    ("Tech Book History Club", "Special Interest"),
    ("Tech Chapter of American Indian Science and Engineering Society", "Engineering/Professional"),
    ("Tech Chinese Language and Culture Association", "Cultural/International"),
    ("Tech Choirs", "Arts/Performance"),
    ("Tech Classical Society", "Academic/Departmental"),
    ("Tech Climbing Club", "Sports/Recreation"),
    ("Tech Club Baseball", "Sports/Recreation"),
    ("Tech Club Hockey", "Sports/Recreation"),
    ("Tech Club Water Polo Team", "Sports/Recreation"),
    ("Tech College Republicans", "Political/Advocacy"),
    ("Tech Council on Family Relations", "Academic/Departmental"),
    ("Tech Creative Media Association", "Media/Communication"),
    ("Tech Dairy Science Club", "Agriculture"),
    ("Tech Disc Golf", "Sports/Recreation"),
    ("Tech Economics Association", "Academic/Departmental"),
    ("Tech Emergency Medical Services", "Health/Pre-Professional"),
    ("Tech Entomology Club", "Science/Research"),
    ("Tech Equestrian Team", "Sports/Recreation"),
    ("Tech Esports Association", "Sports/Recreation"),
    ("Tech Feral Cat Coalition", "Service/Philanthropy"),
    ("Tech French Club", "Cultural/International"),
    ("Tech Gender and Sexuality Association", "Advocacy/Inclusion"),
    ("Tech Golf Club", "Sports/Recreation"),
    ("Tech Gymnastics Club", "Sports/Recreation"),
    ("Tech Horn Society", "Arts/Performance"),
    ("Tech Horse Judging Team", "Agriculture"),
    ("Tech Improv Troupe", "Arts/Performance"),
    ("Tech Kahaani Bollywood Dance Team", "Arts/Performance"),
    ("Tech Kpop Club", "Arts/Performance"),
    ("Tech Law Military Association", "Law/Pre-Law"),
    ("Tech Lawn Mower Racing", "Engineering/Competition"),
    ("Tech Magic Club", "Special Interest"),
    ("Tech Marketing Association", "Business/Professional"),
    ("Tech Martial Arts Club", "Sports/Recreation"),
    ("Tech Men's Club Volleyball", "Sports/Recreation"),
    ("Tech Men's Lacrosse Club", "Sports/Recreation"),
    ("Tech Men's Rugby Club", "Sports/Recreation"),
    ("Tech Men's Soccer Club", "Sports/Recreation"),
    ("Tech Minorities And Philosophy", "Academic/Departmental"),
    ("Tech National Retail Federation Student Association", "Business/Professional"),
    ("Tech Philosophy Club", "Academic/Departmental"),
    ("Tech Photo Club", "Arts/Design"),
    ("Tech Pokémon", "Special Interest"),
    ("Tech Polo Club", "Sports/Recreation"),
    ("Tech Pre-Occupational Therapy Club", "Health/Pre-Professional"),
    ("Tech Pre-Pharmacy Club", "Health/Pre-Professional"),
    ("Tech Pre-Vet Society", "Veterinary"),
    ("Tech Print Club", "Arts/Design"),
    ("Tech Research Club", "Science/Research"),
    ("Tech Robotics Association", "Engineering/Competition"),
    ("Tech RPG Club", "Special Interest"),
    ("Tech Russian and Slavic Association", "Cultural/International"),
    ("Tech Secular Student Alliance", "Religious/Spiritual"),
    ("Tech Shelter Medicine Club", "Veterinary"),
    ("Tech Society for Human Resource Management", "Business/Professional"),
    ("Tech Sport Management Group", "Business/Professional"),
    ("Tech Student Association for Women's Health", "Health/Wellness"),
    ("Tech Student Chapter of the American Choral Directors Association", "Arts/Performance"),
    ("Tech Student Chapter of the American College of Veterinary Pathologists", "Veterinary"),
    ("Tech Student Subunit of the Texas Chapter of the American Fisheries Society", "Science/Research"),
    ("Tech Supply Chain Association", "Business/Professional"),
    ("Tech Swimming", "Sports/Recreation"),
    ("Tech Taara", "Arts/Performance"),
    ("Tech Tennis Club", "Sports/Recreation"),
    ("Tech Terry Scholars", "Academic/Honor Society"),
    ("Tech the Vote", "Political/Advocacy"),
    ("Tech Thoma Scholars", "Academic/Honor Society"),
    ("Tech Trap & Skeet Club", "Sports/Recreation"),
    ("Tech UNICEF", "Service/Philanthropy"),
    ("Tech Women in High Performance Computing", "Technology/Computing"),
    ("Tech Women's Club Soccer", "Sports/Recreation"),
    ("Tech Women's Club Volleyball", "Sports/Recreation"),
    ("Tech Women's Lacrosse Club", "Sports/Recreation"),
    ("Tech Women's Rugby Football Club", "Sports/Recreation"),
    ("Tech Yugioh Club", "Special Interest"),
    ("Texas Aggie Bar Association", "Law/Pre-Law"),
    ("Texas Society of Professional Engineers", "Engineering/Professional"),
    ("Texas Tech Law Review", "Law/Pre-Law"),
    ("Texas Tech Spirit Program", "Spirit/Traditions"),
    ("The Biochemical Society at Tech", "Science/Research"),
    ("The Electrochemical Society", "Science/Research"),
    ("The Journey at Southcrest", "Religious/Spiritual"),
    ("The Masked Bakers", "Special Interest"),
    ("The Math Club", "Academic/Departmental"),
    ("The National Society of Collegiate Scholars", "Academic/Honor Society"),
    ("The National Society of Leadership and Success", "Academic/Honor Society"),
    ("The Raiders Chapter of the Association for Women in Mathematics", "Academic/Departmental"),
    ("The Rotaract Club of Costa Rica/Raiders Service Team", "Service/Philanthropy"),
    ("The Structural Engineers Association of Texas", "Engineering/Professional"),
    ("The Student Chapter of the Society for Range Management at Tech", "Agriculture"),
    ("The Texas Bank Lawyer", "Law/Pre-Law"),
    ("The Way", "Religious/Spiritual"),
    ("The Wildlife Society at Tech", "Science/Research"),
    ("Transfer Techsans", "Special Interest"),
    ("Tree Of Restoration", "Religious/Spiritual"),
    ("TTU SVM Food Animal Club", "Veterinary"),
    ("Turkish Student Association", "Cultural/International"),
    ("Turning Point USA at Tech", "Political/Advocacy"),
    ("U at South Plains Campus Ministry", "Religious/Spiritual"),
    ("Ukrainian Club", "Cultural/International"),
    ("Ultimate Frisbee Club", "Sports/Recreation"),
    ("United States Institute for Theatre Technology Student Chapter", "Arts/Performance"),
    ("Veterinary Business Management Association", "Veterinary"),
    ("Victory Life College Ministry", "Religious/Spiritual"),
    ("Vitality Dance Company", "Arts/Performance"),
    ("Vocal Synth Club", "Arts/Performance"),
    ("We Impact Supply Chain Excellence", "Business/Professional"),
    ("We Make Movies", "Media/Communication"),
    ("Wesley at Tx Tech", "Religious/Spiritual"),
    ("West Texas Association for Botany", "Science/Research"),
    ("Whitacre College of Engineering Outreach Raiders", "Service/Philanthropy"),
    ("Wildlife Medicine Club", "Veterinary"),
    ("Women In Business", "Business/Professional"),
    ("Women in Engineering", "Engineering/Professional"),
    ("Women in Physics", "Science/Research"),
    ("Women in Pre-Law Society", "Law/Pre-Law"),
    ("Women in STEM", "Science/Research"),
    ("Women's Service Organization", "Service/Philanthropy"),
    ("Wool Judging Team", "Agriculture"),
    ("Yellow Caped Raiders", "Service/Philanthropy"),
    ("Young Conservatives of Texas", "Political/Advocacy"),
    ("Young Professionals for CASA", "Service/Philanthropy"),
    ("Young Professionals of Texas Tech", "Business/Professional"),
    ("Zamo Raiders", "Special Interest"),
]

# ON CONFLICT makes re-seeding safe: rerunning this script will not duplicate
# rows, and will not overwrite descriptions already filled in by hand.
INSERT_QUERY = """
INSERT INTO campus_orgs (org_name, category, description, meeting_info)
VALUES (%s, %s, %s, %s)
ON CONFLICT (org_name) DO NOTHING
"""


def seed_database():
    rows = [(name, category, None, None) for name, category in ORGS]

    with closing(get_connection()) as conn:
        with conn, conn.cursor() as cursor:
            cursor.executemany(INSERT_QUERY, rows)
            inserted = cursor.rowcount

    skipped = len(rows) - inserted
    print(f"Seeding complete: {inserted} inserted, {skipped} already present.")


if __name__ == "__main__":
    seed_database()
