import json
import re
from contextlib import closing
from pathlib import Path
from psycopg2.extras import execute_values
from db import get_connection

BACKEND_DIR = Path(__file__).parent.parent / "backend"


# Read one of the backend's JSON data files.
def load_backend_json(filename):
    with (BACKEND_DIR / filename).open(encoding="utf-8") as file:
        return json.load(file)


# Load the tagged organizations, each organization's Instagram username,
# and the events collected from those Instagram accounts.
tagged_orgs = load_backend_json("org.json")
instagram_usernames = load_backend_json("orgmap.json")
events = load_backend_json("events.json")

# The rest of the campus catalog, ordered alphabetically as published.
# Organizations already in backend/org.json are left out of this list.
# IDs continue after the ones in org.json and are written out here so they
# never shift when an organization is added or removed.
# Categories use the same names as backend/org.json, with extra ones for
# groups org.json has no category for (such as Law or Religious/Spiritual).
# Tags are generated below; contact and meeting time stay empty until real
# data is collected.
CATALOG_ORGS = [
    ("org_036", "A Dog's Way Home", "Community Service"),
    ("org_037", "Adventist Christian Fellowship", "Religious/Spiritual"),
    ("org_038", "Ag Eco Competitive Club", "Agricultural Sciences & Natural Resources"),
    ("org_039", "Agricultural Communicators of Tomorrow", "Agricultural Sciences & Natural Resources"),
    ("org_040", "Agricultural Economics Grad Student Association", "Agricultural Sciences & Natural Resources"),
    ("org_041", "Agricultural Education and Communications Graduate Organization", "Agricultural Sciences & Natural Resources"),
    ("org_042", "Agricultural Educators of Tomorrow", "Agricultural Sciences & Natural Resources"),
    ("org_043", "Agricultural Law Association", "Law"),
    ("org_044", "AjedRaiders", "Gaming"),
    ("org_045", "Alpha Lambda Delta & PES", "Honor Society"),
    ("org_046", "Alpha Psi Omega", "Music/Art"),
    ("org_047", "Alpha Zeta", "Honor Society"),
    ("org_048", "Ambassadors for Agriculture", "Agricultural Sciences & Natural Resources"),
    ("org_049", "American Association Of Drilling Engineers", "Engineering / Computer Science"),
    ("org_050", "American Association of Family & Consumer Sciences-Family, Career and Community Leaders of America", "Health & Human Sciences"),
    ("org_051", "American Association of Petroleum Geologists Student Chapter", "Arts & Sciences"),
    ("org_052", "American Institute of Chemical Engineers", "Engineering / Computer Science"),
    ("org_053", "American Institute of Graphic Arts", "Music/Art"),
    ("org_054", "American Medical Women's Association", "Health & Human Sciences"),
    ("org_055", "American Rock Mechanics Association", "Engineering / Computer Science"),
    ("org_056", "American Society of Civil Engineers", "Engineering / Computer Science"),
    ("org_057", "American Society of Interior Designers", "Music/Art"),
    ("org_058", "American Society of Mechanical Engineers", "Engineering / Computer Science"),
    ("org_059", "American String Teachers Association", "Music/Art"),
    ("org_060", "Anchor Student Club", "Religious/Spiritual"),
    ("org_061", "Animal and Food Science Academic Quadrathlon", "Agricultural Sciences & Natural Resources"),
    ("org_062", "Arnold Air Society Spencer Brian LaBrie Squadron", "Military/Veterans"),
    ("org_063", "Associated General Contractors", "Engineering / Computer Science"),
    ("org_064", "Association for Competitive Math Olympics", "Arts & Sciences"),
    ("org_065", "Association of Bangladeshi Students and Scholars", "Culture/Nationality"),
    ("org_066", "Association of Competitive Engineers", "Engineering / Computer Science"),
    ("org_067", "Association of Information Technology Professionals", "Engineering / Computer Science"),
    ("org_068", "Association of Students Acting in Service", "Community Service"),
    ("org_069", "Atlas Campus Fellowship", "Religious/Spiritual"),
    ("org_070", "Ballroom Dance at Tech", "Music/Art"),
    ("org_071", "Baptist Student Ministry", "Religious/Spiritual"),
    ("org_072", "Beta Beta Beta- Nu Alpha Chapter", "Honor Society"),
    ("org_073", "Beta Gamma Sigma", "Honor Society"),
    ("org_074", "Beyond Barriers - Inclusive Learning Advocates for Accessible Education", "Political/Advocacy"),
    ("org_075", "Biotechnology Organization for Student Success", "Arts & Sciences"),
    ("org_076", "Black Arts Society", "Culture/Nationality"),
    ("org_077", "Black Business Student Association", "Business"),
    ("org_078", "Black Graduate Student Association", "Culture/Nationality"),
    ("org_079", "Black Graduation Alliance", "Culture/Nationality"),
    ("org_080", "Black Law Students Association", "Law"),
    ("org_081", "Black Student Association", "Culture/Nationality"),
    ("org_082", "Blue Book Initiative", "Community Service"),
    ("org_083", "Board Of Barristers", "Law"),
    ("org_084", "Bookmarked Book Club", "Hobbies/Special Interest"),
    ("org_085", "Campus Crusade for Christ", "Religious/Spiritual"),
    ("org_086", "Cancer Advocacy and Research in Biological Sciences", "Arts & Sciences"),
    ("org_087", "Canterbury Episcopal Campus Ministry", "Religious/Spiritual"),
    ("org_088", "Catholic Student Association", "Religious/Spiritual"),
    ("org_089", "Chabad Jewish Student Group", "Religious/Spiritual"),
    ("org_090", "Chemical Engineering Graduate Student Association", "Engineering / Computer Science"),
    ("org_091", "Chemistry Graduate Student Organization", "Arts & Sciences"),
    ("org_092", "Chi Alpha Christian Fellowship", "Religious/Spiritual"),
    ("org_093", "Chi Epsilon", "Honor Society"),
    ("org_094", "Chi Sigma Iota", "Honor Society"),
    ("org_095", "Children's Health and Medical Program", "Health & Human Sciences"),
    ("org_096", "Christian Legal Society", "Religious/Spiritual"),
    ("org_097", "Christian Veterinary Fellowship", "Religious/Spiritual"),
    ("org_098", "Christians At Tech", "Religious/Spiritual"),
    ("org_099", "CISER Scholar Service Organization", "Community Service"),
    ("org_100", "Clay Club", "Music/Art"),
    ("org_101", "Clinical Psychology Graduate Student Council", "Arts & Sciences"),
    ("org_102", "Coalition of Healthcare Students", "Health & Human Sciences"),
    ("org_103", "Coalition/Councils", "Student Government/Leadership"),
    ("org_104", "Codename: Raider", "Hobbies/Special Interest"),
    ("org_105", "CodePath.org", "Engineering / Computer Science"),
    ("org_106", "Collective Action", "Political/Advocacy"),
    ("org_107", "College of Arts & Sciences Student Ambassadors", "Student Government/Leadership"),
    ("org_108", "College of Health and Human Sciences Ambassadors", "Student Government/Leadership"),
    ("org_109", "College of Health and Human Sciences Society of Future Clinicians", "Health & Human Sciences"),
    ("org_110", "College of Human Sciences Dean's Leadership Council (DLC)", "Student Government/Leadership"),
    ("org_111", "College of Media & Communication Graduate Student Society", "Media & Communication"),
    ("org_112", "ColorStack", "Engineering / Computer Science"),
    ("org_113", "Communication Studies Society", "Media & Communication"),
    ("org_114", "Counseling Council", "Education"),
    ("org_115", "Criminal Law Association", "Law"),
    ("org_116", "Cyber Raiders", "Engineering / Computer Science"),
    ("org_117", "Céfiro: Enlace Hispano, Cultural y Literario", "Culture/Nationality"),
    ("org_118", "Daily Toreador", "Media & Communication"),
    ("org_119", "Dancers with Soul: Hip Hop Dance Team", "Music/Art"),
    ("org_120", "Delight Ministries", "Religious/Spiritual"),
    ("org_121", "Democrats for Texas", "Political/Advocacy"),
    ("org_122", "Dirty Techsans", "Hobbies/Special Interest"),
    ("org_123", "Double T Locksport", "Hobbies/Special Interest"),
    ("org_124", "Dr. Bernard Harris Pre-Medical Society", "Health & Human Sciences"),
    ("org_125", "Education Graduate Student Organization", "Education"),
    ("org_126", "El Club de Español", "Culture/Nationality"),
    ("org_127", "Empire A Cappella", "Music/Art"),
    ("org_128", "Energy Law Interest Group", "Law"),
    ("org_129", "Engineering Diplomats", "Student Government/Leadership"),
    ("org_130", "Environmental Law Society", "Law"),
    ("org_131", "Environmental Toxicology Student Association", "Arts & Sciences"),
    ("org_132", "Estate Planning And Community Property Law Journal", "Law"),
    ("org_133", "Eta Omicron Nu", "Honor Society"),
    ("org_134", "Family Business Student Organization", "Business"),
    ("org_135", "Family Law Society", "Law"),
    ("org_136", "Fashion and Media Entertainment", "Music/Art"),
    ("org_137", "First Lubbock College Ministry", "Religious/Spiritual"),
    ("org_138", "Foundation Retreat", "Religious/Spiritual"),
    ("org_139", "Friendly Raiders for Education Equity", "Community Service"),
    ("org_140", "Friends of Médecins Sans Frontières", "Community Service"),
    ("org_141", "Future Lawyers of Today", "Law"),
    ("org_142", "Geography & Youth Mappers", "Arts & Sciences"),
    ("org_143", "Geoscience Student Society", "Arts & Sciences"),
    ("org_144", "Ghana Students Association", "Culture/Nationality"),
    ("org_145", "Goin' Band Student Association", "Music/Art"),
    ("org_146", "Google Developer Student Club", "Engineering / Computer Science"),
    ("org_147", "Graduate Association of Physicists", "Arts & Sciences"),
    ("org_148", "Graduate English Society", "Arts & Sciences"),
    ("org_149", "Graduate Hospitality Management and Retail Association", "Health & Human Sciences"),
    ("org_150", "Graduate Nutrition Organization", "Health & Human Sciences"),
    ("org_151", "Hi-Tech Fashion Group", "Music/Art"),
    ("org_152", "High Riders", "Spirit/Traditions"),
    ("org_153", "Higher Education Student Association", "Education"),
    ("org_154", "Hillel", "Religious/Spiritual"),
    ("org_155", "Hispanic Law Student Association", "Law"),
    ("org_156", "Honors Association for Aspiring Pre-health Tracks", "Health & Human Sciences"),
    ("org_157", "Honors College Bayless Elementary Mentoring Program", "Community Service"),
    ("org_158", "Horticulture Society", "Agricultural Sciences & Natural Resources"),
    ("org_159", "Human Development and Family Sciences and Early Childhood Ambassadors", "Student Government/Leadership"),
    ("org_160", "Human Development And Family Sciences Graduate Student Association", "Health & Human Sciences"),
    ("org_161", "Human Factors And Ergonomics Society", "Engineering / Computer Science"),
    ("org_162", "ICMA Student Chapter Lubbock", "Business"),
    ("org_163", "IDEAL", "Hobbies/Special Interest"),
    ("org_164", "IEEE Eta Kappa Nu", "Honor Society"),
    ("org_165", "IEEE Nuclear & Plasma Sciences Society", "Engineering / Computer Science"),
    ("org_166", "Immigration Law Association", "Law"),
    ("org_167", "INFORMS Student Chapter", "Engineering / Computer Science"),
    ("org_168", "Institute of Industrial and Systems Engineers", "Engineering / Computer Science"),
    ("org_169", "Intellectual Property Student Association", "Law"),
    ("org_170", "International Association of Business Communicators Tech Student Chapter", "Media & Communication"),
    ("org_171", "International Association of Drilling Contractors", "Engineering / Computer Science"),
    ("org_172", "International Interior Design Association", "Music/Art"),
    ("org_173", "Involvement Ambassadors", "Student Government/Leadership"),
    ("org_174", "Iota Iota Iota", "Honor Society"),
    ("org_175", "Iota Tau Alpha", "Honor Society"),
    ("org_176", "Japanese Student Association", "Culture/Nationality"),
    ("org_177", "JINXX!", "Music/Art"),
    ("org_178", "Journal of Technology, Law, and Society", "Law"),
    ("org_179", "Journal of the Energy Law Practitioner", "Law"),
    ("org_180", "JoyCentric Organization", "Community Service"),
    ("org_181", "Kinesiology and Sport Management Ambassadors", "Student Government/Leadership"),
    ("org_182", "Knight Raiders", "Gaming"),
    ("org_183", "Knights of Architecture", "Music/Art"),
    ("org_184", "Knowledge Empowering You", "Community Service"),
    ("org_185", "Korean Student Association", "Culture/Nationality"),
    ("org_186", "Latino Medical Student Association Plus", "Health & Human Sciences"),
    ("org_187", "Latter-Day Saint Student Association", "Religious/Spiritual"),
    ("org_188", "Live Oak College Ministry", "Religious/Spiritual"),
    ("org_189", "Livestock Judging Team", "Agricultural Sciences & Natural Resources"),
    ("org_190", "Llano Estacado Student Chapter Of The Society Of Environmental Toxicology And Chemistry", "Arts & Sciences"),
    ("org_191", "Lubbock Rotaract Club", "Community Service"),
    ("org_192", "Lutheran Student Fellowship", "Religious/Spiritual"),
    ("org_193", "Managing Leaders Association", "Business"),
    ("org_194", "Mantra Meditation", "Religious/Spiritual"),
    ("org_195", "Matador Collegiate Farm Bureau", "Agricultural Sciences & Natural Resources"),
    ("org_196", "Matador MMA", "Gym/Fitness"),
    ("org_197", "Meat Animal Evaluation Team", "Agricultural Sciences & Natural Resources"),
    ("org_198", "Meat Judging Team", "Agricultural Sciences & Natural Resources"),
    ("org_199", "Meat Science Academic Quiz Bowl Team", "Agricultural Sciences & Natural Resources"),
    ("org_200", "Meat Science Association", "Agricultural Sciences & Natural Resources"),
    ("org_201", "Medical and Dental Global Brigades", "Community Service"),
    ("org_202", "Mediterranean Student Society", "Culture/Nationality"),
    ("org_203", "MedLife", "Community Service"),
    ("org_204", "Metals Club", "Music/Art"),
    ("org_205", "MindMatters", "Health & Human Sciences"),
    ("org_206", "Minorities in Pre Law Alliance", "Law"),
    ("org_207", "Minority Association of Pre-Health Students", "Health & Human Sciences"),
    ("org_208", "Miracle Pennies College Edition", "Community Service"),
    ("org_209", "Missionary Baptist Student Fellowship", "Religious/Spiritual"),
    ("org_210", "Model United Nations", "Arts & Sciences"),
    ("org_211", "Mortar Board", "Honor Society"),
    ("org_212", "Mu Epsilon Kappa Anime", "Hobbies/Special Interest"),
    ("org_213", "Multicultural Pre-Dental Association", "Health & Human Sciences"),
    ("org_214", "Multicultural Student Business Association", "Business"),
    ("org_215", "Museum Heritage Student Association", "Arts & Sciences"),
    ("org_216", "Muslim Student Association", "Religious/Spiritual"),
    ("org_217", "NAACP @ Tech", "Political/Advocacy"),
    ("org_218", "National Association of Teachers of Singing at Tech", "Music/Art"),
    ("org_219", "National Marrow Donation Program", "Community Service"),
    ("org_220", "National Organization of Minority Architect Students Lubbock Chapter", "Music/Art"),
    ("org_221", "Navigators", "Religious/Spiritual"),
    ("org_222", "Nepal Students Association", "Culture/Nationality"),
    ("org_223", "Network of Enlightened Women", "Political/Advocacy"),
    ("org_224", "Nigerian Students Association", "Culture/Nationality"),
    ("org_225", "No Mind Left Behind", "Community Service"),
    ("org_226", "Non-Traditional Law Student Association", "Law"),
    ("org_227", "Organization Of Women Law Students", "Law"),
    ("org_228", "Orthodox Christian Fellowship", "Religious/Spiritual"),
    ("org_229", "OUTlaw", "Law"),
    ("org_230", "Peers Against Tobacco", "Health & Human Sciences"),
    ("org_231", "Personal Financial Planning Association", "Business"),
    ("org_232", "Pets Are Worth Saving", "Community Service"),
    ("org_233", "Phi Alpha Theta: Zeta-Iota Chapter", "Honor Society"),
    ("org_234", "Phi Upsilon Omicron", "Honor Society"),
    ("org_235", "Philosophy Graduate Student Association", "Arts & Sciences"),
    ("org_236", "Physician Assistant Student Organization", "Health & Human Sciences"),
    ("org_237", "Pi Tau Sigma", "Honor Society"),
    ("org_238", "Plant and Soil Science Graduate Council", "Agricultural Sciences & Natural Resources"),
    ("org_239", "Pre-Athletic Training Club", "Health & Human Sciences"),
    ("org_240", "Pre-Optometry Professional Society", "Health & Human Sciences"),
    ("org_241", "Pre-Physical Therapy Club", "Health & Human Sciences"),
    ("org_242", "President's Select", "Student Government/Leadership"),
    ("org_243", "Prosecution Law Association", "Law"),
    ("org_244", "Providing the Outside World with Empowerment and Resources", "Community Service"),
    ("org_245", "Psi Chi: International Honor Society In Psychology", "Honor Society"),
    ("org_246", "Public Relations Student Society of America", "Media & Communication"),
    ("org_247", "Raider Aerospace Society", "Engineering / Computer Science"),
    ("org_248", "Raider Badminton Club", "Sports"),
    ("org_249", "Raider Bar Association", "Law"),
    ("org_250", "Raider Calisthenics Club", "Gym/Fitness"),
    ("org_251", "Raider Historical Fencing", "Sports"),
    ("org_252", "Raider Medical Screening Society", "Health & Human Sciences"),
    ("org_253", "Raider Power of Paranormal", "Hobbies/Special Interest"),
    ("org_254", "Raider Precision Rifle Club", "Outdoor Activities"),
    ("org_255", "Raider Recycling", "Community Service"),
    ("org_256", "Raider Red's Food Pantry", "Community Service"),
    ("org_257", "Raider Rhetoric Society", "Media & Communication"),
    ("org_258", "Raider Riot", "Spirit/Traditions"),
    ("org_259", "Raider Trumpet Guild", "Music/Art"),
    ("org_260", "Raider's Knit & Knot", "Hobbies/Special Interest"),
    ("org_261", "Raiders American Society of Microbiology Undergraduate Chapter", "Arts & Sciences"),
    ("org_262", "Raiders for Life", "Political/Advocacy"),
    ("org_263", "Raiders for Reproductive Rights", "Political/Advocacy"),
    ("org_264", "Raiders of The Law", "Law"),
    ("org_265", "Raiders Uncorked", "Hobbies/Special Interest"),
    ("org_266", "Rawls Banking Association", "Business"),
    ("org_267", "Rawls College of Business Dean's Student Council", "Student Government/Leadership"),
    ("org_268", "Rawls Global Business Council", "Business"),
    ("org_269", "Rawls Graduate Association", "Business"),
    ("org_270", "Real Estate Organization", "Business"),
    ("org_271", "Red Costa Rica Female Futbol Club", "Sports"),
    ("org_272", "Red Costa Rica Men's Futbol Club", "Sports"),
    ("org_273", "Red Dirt Racing", "Engineering / Computer Science"),
    ("org_274", "Red PlaNet", "Hobbies/Special Interest"),
    ("org_275", "Red Raider Camp", "Spirit/Traditions"),
    ("org_276", "Red Raider Racing", "Engineering / Computer Science"),
    ("org_277", "Red Theatre Company", "Music/Art"),
    ("org_278", "Redeemed Christian Church of God, Dominion Chapel Fellowship", "Religious/Spiritual"),
    ("org_279", "Redeemer College Ministry", "Religious/Spiritual"),
    ("org_280", "Reformed University Fellowship", "Religious/Spiritual"),
    ("org_281", "Renewable Energy Student Association", "Engineering / Computer Science"),
    ("org_282", "Robotics and Advanced Tech Society", "Engineering / Computer Science"),
    ("org_283", "Sabre Flight Drill Team", "Military/Veterans"),
    ("org_284", "Saddle Tramps", "Spirit/Traditions"),
    ("org_285", "Sales Leadership Group", "Business"),
    ("org_286", "School of Veterinary Medicine Companion Animal Club", "Veterinary Medicine"),
    ("org_287", "School of Veterinary Medicine Graduate Student Association", "Veterinary Medicine"),
    ("org_288", "Script Raiders", "Media & Communication"),
    ("org_289", "Sigma Delta Pi", "Honor Society"),
    ("org_290", "Sigma Tau Delta", "Honor Society"),
    ("org_291", "Signing Raiders", "Political/Advocacy"),
    ("org_292", "Skyraiders", "Outdoor Activities"),
    ("org_293", "Social Work Student Organization", "Arts & Sciences"),
    ("org_294", "Society For Industrial And Applied Mathematics", "Arts & Sciences"),
    ("org_295", "Society Of Environmental Professionals", "Arts & Sciences"),
    ("org_296", "Society Of Petroleum Engineers", "Engineering / Computer Science"),
    ("org_297", "Society of Plastics Engineers", "Engineering / Computer Science"),
    ("org_298", "Society of Professional Journalists", "Media & Communication"),
    ("org_299", "South Asian Student Association", "Culture/Nationality"),
    ("org_300", "Space Exploration Raiders", "Arts & Sciences"),
    ("org_301", "Special Olympics College", "Community Service"),
    ("org_302", "Sport Club Executive Council", "Sports"),
    ("org_303", "Sport Club Supervisors", "Sports"),
    ("org_304", "Sports and Entertainment Law Society", "Law"),
    ("org_305", "Sri Lankan Students Association", "Culture/Nationality"),
    ("org_306", "Student Activities Board", "Student Government/Leadership"),
    ("org_307", "Student Agricultural and Natural Resources Council", "Agricultural Sciences & Natural Resources"),
    ("org_308", "Student Alumni Board", "Student Government/Leadership"),
    ("org_309", "Student Association for Fire Ecology", "Agricultural Sciences & Natural Resources"),
    ("org_310", "Student Association Of Marriage And Family Therapy", "Health & Human Sciences"),
    ("org_311", "Student Bar Association", "Law"),
    ("org_312", "Student Chapter of the American Association of Equine Practitioners", "Veterinary Medicine"),
    ("org_313", "Student Chapter of the American Meteorological Society at Tech", "Arts & Sciences"),
    ("org_314", "Student Government Association", "Student Government/Leadership"),
    ("org_315", "Student Mobilization", "Religious/Spiritual"),
    ("org_316", "Student Nutrition Organization", "Health & Human Sciences"),
    ("org_317", "Student Organ Donation Advocates", "Community Service"),
    ("org_318", "Student Union & Activities Community Outreach", "Community Service"),
    ("org_319", "Student Veterans of America", "Military/Veterans"),
    ("org_320", "Student Veterinary Emergency Response Association", "Veterinary Medicine"),
    ("org_321", "Student Veterinary Surgical Society", "Veterinary Medicine"),
    ("org_322", "Students of East Africa at Tech", "Culture/Nationality"),
    ("org_323", "Studio Hacks", "Music/Art"),
    ("org_324", "Tau Beta Pi", "Honor Society"),
    ("org_325", "Teaching Techsans", "Education"),
    ("org_326", "Tech Advertising Federation", "Media & Communication"),
    ("org_327", "Tech American Society for Microbiology", "Arts & Sciences"),
    ("org_328", "Tech Archery Club", "Outdoor Activities"),
    ("org_329", "Tech Astronomy Club", "Arts & Sciences"),
    ("org_330", "Tech Athletic Ambassadors", "Spirit/Traditions"),
    ("org_331", "Tech Bass Fishing Team", "Outdoor Activities"),
    ("org_332", "Tech Board Game Club", "Gaming"),
    ("org_333", "Tech Book History Club", "Hobbies/Special Interest"),
    ("org_334", "Tech Chapter of American Indian Science and Engineering Society", "Engineering / Computer Science"),
    ("org_335", "Tech Chinese Language and Culture Association", "Culture/Nationality"),
    ("org_336", "Tech Classical Society", "Arts & Sciences"),
    ("org_337", "Tech Climbing Club", "Outdoor Activities"),
    ("org_338", "Tech Club Baseball", "Sports"),
    ("org_339", "Tech Club Hockey", "Sports"),
    ("org_340", "Tech Club Water Polo Team", "Sports"),
    ("org_341", "Tech College Republicans", "Political/Advocacy"),
    ("org_342", "Tech Council on Family Relations", "Health & Human Sciences"),
    ("org_343", "Tech Creative Media Association", "Media & Communication"),
    ("org_344", "Tech Dairy Science Club", "Agricultural Sciences & Natural Resources"),
    ("org_345", "Tech Disc Golf", "Outdoor Activities"),
    ("org_346", "Tech Economics Association", "Arts & Sciences"),
    ("org_347", "Tech Emergency Medical Services", "Health & Human Sciences"),
    ("org_348", "Tech Entomology Club", "Agricultural Sciences & Natural Resources"),
    ("org_349", "Tech Equestrian Team", "Sports"),
    ("org_350", "Tech Feral Cat Coalition", "Community Service"),
    ("org_351", "Tech French Club", "Culture/Nationality"),
    ("org_352", "Tech Gender and Sexuality Association", "Political/Advocacy"),
    ("org_353", "Tech Golf Club", "Sports"),
    ("org_354", "Tech Gymnastics Club", "Sports"),
    ("org_355", "Tech Horn Society", "Music/Art"),
    ("org_356", "Tech Horse Judging Team", "Agricultural Sciences & Natural Resources"),
    ("org_357", "Tech Improv Troupe", "Music/Art"),
    ("org_358", "Tech Kahaani Bollywood Dance Team", "Music/Art"),
    ("org_359", "Tech Kpop Club", "Music/Art"),
    ("org_360", "Tech Law Military Association", "Law"),
    ("org_361", "Tech Lawn Mower Racing", "Engineering / Computer Science"),
    ("org_362", "Tech Magic Club", "Hobbies/Special Interest"),
    ("org_363", "Tech Martial Arts Club", "Gym/Fitness"),
    ("org_364", "Tech Men's Club Volleyball", "Sports"),
    ("org_365", "Tech Men's Lacrosse Club", "Sports"),
    ("org_366", "Tech Men's Rugby Club", "Sports"),
    ("org_367", "Tech Men's Soccer Club", "Sports"),
    ("org_368", "Tech Minorities And Philosophy", "Arts & Sciences"),
    ("org_369", "Tech National Retail Federation Student Association", "Business"),
    ("org_370", "Tech Philosophy Club", "Arts & Sciences"),
    ("org_371", "Tech Photo Club", "Music/Art"),
    ("org_372", "Tech Pokémon", "Gaming"),
    ("org_373", "Tech Polo Club", "Sports"),
    ("org_374", "Tech Pre-Occupational Therapy Club", "Health & Human Sciences"),
    ("org_375", "Tech Pre-Pharmacy Club", "Health & Human Sciences"),
    ("org_376", "Tech Pre-Vet Society", "Veterinary Medicine"),
    ("org_377", "Tech Print Club", "Music/Art"),
    ("org_378", "Tech Research Club", "Arts & Sciences"),
    ("org_379", "Tech Robotics Association", "Engineering / Computer Science"),
    ("org_380", "Tech RPG Club", "Gaming"),
    ("org_381", "Tech Russian and Slavic Association", "Culture/Nationality"),
    ("org_382", "Tech Secular Student Alliance", "Religious/Spiritual"),
    ("org_383", "Tech Shelter Medicine Club", "Veterinary Medicine"),
    ("org_384", "Tech Society for Human Resource Management", "Business"),
    ("org_385", "Tech Sport Management Group", "Business"),
    ("org_386", "Tech Student Association for Women's Health", "Health & Human Sciences"),
    ("org_387", "Tech Student Chapter of the American Choral Directors Association", "Music/Art"),
    ("org_388", "Tech Student Chapter of the American College of Veterinary Pathologists", "Veterinary Medicine"),
    ("org_389", "Tech Student Subunit of the Texas Chapter of the American Fisheries Society", "Agricultural Sciences & Natural Resources"),
    ("org_390", "Tech Supply Chain Association", "Business"),
    ("org_391", "Tech Swimming", "Sports"),
    ("org_392", "Tech Taara", "Music/Art"),
    ("org_393", "Tech Tennis Club", "Sports"),
    ("org_394", "Tech Terry Scholars", "Honor Society"),
    ("org_395", "Tech the Vote", "Political/Advocacy"),
    ("org_396", "Tech Thoma Scholars", "Honor Society"),
    ("org_397", "Tech Trap & Skeet Club", "Outdoor Activities"),
    ("org_398", "Tech UNICEF", "Community Service"),
    ("org_399", "Tech Women in High Performance Computing", "Engineering / Computer Science"),
    ("org_400", "Tech Women's Club Soccer", "Sports"),
    ("org_401", "Tech Women's Club Volleyball", "Sports"),
    ("org_402", "Tech Women's Lacrosse Club", "Sports"),
    ("org_403", "Tech Women's Rugby Football Club", "Sports"),
    ("org_404", "Tech Yugioh Club", "Gaming"),
    ("org_405", "Texas Aggie Bar Association", "Law"),
    ("org_406", "Texas Society of Professional Engineers", "Engineering / Computer Science"),
    ("org_407", "Texas Tech Law Review", "Law"),
    ("org_408", "Texas Tech Spirit Program", "Spirit/Traditions"),
    ("org_409", "The Biochemical Society at Tech", "Arts & Sciences"),
    ("org_410", "The Electrochemical Society", "Arts & Sciences"),
    ("org_411", "The Journey at Southcrest", "Religious/Spiritual"),
    ("org_412", "The Masked Bakers", "Hobbies/Special Interest"),
    ("org_413", "The National Society of Collegiate Scholars", "Honor Society"),
    ("org_414", "The National Society of Leadership and Success", "Honor Society"),
    ("org_415", "The Raiders Chapter of the Association for Women in Mathematics", "Arts & Sciences"),
    ("org_416", "The Rotaract Club of Costa Rica/Raiders Service Team", "Community Service"),
    ("org_417", "The Structural Engineers Association of Texas", "Engineering / Computer Science"),
    ("org_418", "The Student Chapter of the Society for Range Management at Tech", "Agricultural Sciences & Natural Resources"),
    ("org_419", "The Texas Bank Lawyer", "Law"),
    ("org_420", "The Way", "Religious/Spiritual"),
    ("org_421", "The Wildlife Society at Tech", "Agricultural Sciences & Natural Resources"),
    ("org_422", "Transfer Techsans", "Hobbies/Special Interest"),
    ("org_423", "Tree Of Restoration", "Religious/Spiritual"),
    ("org_424", "TTU SVM Food Animal Club", "Veterinary Medicine"),
    ("org_425", "Turkish Student Association", "Culture/Nationality"),
    ("org_426", "Turning Point USA at Tech", "Political/Advocacy"),
    ("org_427", "U at South Plains Campus Ministry", "Religious/Spiritual"),
    ("org_428", "Ukrainian Club", "Culture/Nationality"),
    ("org_429", "Ultimate Frisbee Club", "Sports"),
    ("org_430", "United States Institute for Theatre Technology Student Chapter", "Music/Art"),
    ("org_431", "Veterinary Business Management Association", "Veterinary Medicine"),
    ("org_432", "Victory Life College Ministry", "Religious/Spiritual"),
    ("org_433", "Vitality Dance Company", "Music/Art"),
    ("org_434", "Vocal Synth Club", "Music/Art"),
    ("org_435", "We Impact Supply Chain Excellence", "Business"),
    ("org_436", "We Make Movies", "Media & Communication"),
    ("org_437", "Wesley at Tx Tech", "Religious/Spiritual"),
    ("org_438", "West Texas Association for Botany", "Arts & Sciences"),
    ("org_439", "Whitacre College of Engineering Outreach Raiders", "Community Service"),
    ("org_440", "Wildlife Medicine Club", "Veterinary Medicine"),
    ("org_441", "Women in Engineering", "Engineering / Computer Science"),
    ("org_442", "Women in Physics", "Arts & Sciences"),
    ("org_443", "Women in Pre-Law Society", "Law"),
    ("org_444", "Women in STEM", "Arts & Sciences"),
    ("org_445", "Women's Service Organization", "Community Service"),
    ("org_446", "Wool Judging Team", "Agricultural Sciences & Natural Resources"),
    ("org_447", "Yellow Caped Raiders", "Community Service"),
    ("org_448", "Young Conservatives of Texas", "Political/Advocacy"),
    ("org_449", "Young Professionals for CASA", "Community Service"),
    ("org_450", "Young Professionals of Texas Tech", "Business"),
    ("org_451", "Zamo Raiders", "Hobbies/Special Interest"),
]

# Tags for the catalog orgs, in the same style as backend/org.json: broad
# interest tags come from the category, and specific hobby tags from words in
# the organization's name. Tag names match the options on the interest
# checklist (lowercased), so students' picks line up with them.
CATEGORY_INTEREST_TAGS = {
    "Agricultural Sciences & Natural Resources": ["agriculture", "environment", "outdoors", "animals"],
    "Arts & Sciences": ["stem", "research", "academic"],
    "Business": ["business", "entrepreneurship", "finance"],
    "Engineering / Computer Science": ["technology", "stem", "engineering"],
    "Health & Human Sciences": ["health", "medicine", "wellness"],
    "Culture/Nationality": ["culture", "community", "identity"],
    "Gym/Fitness": ["fitness"],
    "Outdoor Activities": ["outdoors"],
    "Music/Art": ["arts"],
    "Gaming": ["gaming"],
    "Community Service": ["volunteering", "community service"],
    "Education": ["academic", "mentorship"],
    "Law": ["law", "politics"],
    "Media & Communication": ["media", "writing"],
    "Veterinary Medicine": ["animals", "medicine", "health"],
    "Religious/Spiritual": ["faith", "community"],
    "Political/Advocacy": ["politics", "inclusion"],
    "Sports": ["sports", "fitness"],
    "Hobbies/Special Interest": ["community"],
    "Honor Society": ["academic", "leadership"],
    "Student Government/Leadership": ["leadership", "community"],
    "Spirit/Traditions": ["school spirit", "community"],
    "Military/Veterans": ["military", "leadership"],
}

# (pattern matched against the name, hobby tags to add)
NAME_HOBBY_TAGS = [
    (r"danc|ballroom|hip hop|bollywood|kahaani|taara|kpop", ["dance", "performance"]),
    (r"a cappella|choir|choral|singing|vocal", ["singing", "music", "performance"]),
    (r"theat|improv|jinxx", ["theater", "performance"]),
    (r"\bband\b|trumpet|horn society|string|music|goin' band", ["music", "performance"]),
    (r"photo", ["photography"]),
    (r"film|movie|creative media|script", ["film"]),
    (r"journal|toreador|rhetoric|law review|book|english society|script|bank lawyer", ["writing"]),
    (r"soccer|futbol|volleyball|rugby|lacrosse|hockey|baseball|tennis|golf|swim|polo|badminton|frisbee|gymnastic|equestrian|fencing|sport club", ["sports"]),
    (r"climb|backpack", ["hiking", "camping"]),
    (r"fishing|archery|skeet|rifle|disc golf|skyraiders|wildlife society|range management|fire ecology", ["outdoors"]),
    (r"powerlifting|calisthenics", ["weightlifting", "gym"]),
    (r"\bmma\b|martial", ["gym"]),
    (r"chess|ajedraiders|knight raiders|board game|\brpg\b|yugioh|pok[eé]mon|magic club", ["gaming"]),
    (r"esports|video game", ["esports", "video games"]),
    (r"robot|racing|aerospace|computing|developer|cyber|codepath|colorstack|hacks|electrical and electronics|high performance computing", ["technology"]),
    (r"pre-(med|dental|nursing|pharmacy|optometry|physical|occupational|athletic|health)|medical|medicine|dental|physician|health|emergency medical", ["health", "medicine"]),
    (r"volunteer|service|pantry|recycling|unicef|special olympics|best buddies|rotaract|casa\b|outreach|donation|miracle pennies|habitat", ["volunteering", "community service"]),
    (r"mentor|tutor|teach|ambassador|diplomat", ["mentorship"]),
    (r"women|minorit|black|hispanic|latin|asian|african|gender|inclusi|accessib|naacp|signing|multicultural|non-traditional|transfer", ["inclusion", "identity"]),
    (r"entrepreneur|startup", ["entrepreneurship"]),
    (r"financ|investment|banking|real estate", ["finance"]),
    (r"environment|renewable|wildlife|botany|fire ecology|recycling|toxicolog|fisheries|geograph|meteorolog", ["environment"]),
    (r"animal|\bpets\b|cat coalition|veterinar|equine|dog|shelter|meat|livestock|cattle|horse|wool|dairy|block & bridle", ["animals"]),
    (r"research|biotech|biochem|cancer|microbiology|astronomy|physicists|forensic", ["research"]),
    (r"meditation|mindmatters|wellness|nutrition|tobacco", ["wellness"]),
    (r"democrat|republican|conservative|\bvote\b|turning point|collective action|raiders for life|reproductive|enlightened women", ["politics"]),
    (r"leader|government|executive|dean's|president's|activities board|alumni board|councils|involvement", ["leadership"]),
    (r"christian|catholic|baptist|ministry|fellowship|church|hillel|chabad|jewish|muslim|latter-day|lutheran|episcopal|orthodox|campus crusade|navigators|wesley|secular|delight|redeemer|tree of restoration|student mobilization|foundation retreat|mantra|\bthe way\b|journey at", ["faith"]),
]

# (pattern matched against the name, culture tag). The first match wins.
NAME_CULTURE_TAGS = [
    (r"hispanic|latin|español|céfiro|costa rica", "Hispanic/Latino"),
    (r"caribbean", "Caribbean"),
    (r"black|african|nigerian|ghana|east africa|naacp", "African/Black"),
    (r"filipino", "Filipino"),
    (r"asian|korean|japanese|chinese|bangladeshi|nepal|sri lankan|bollywood|kahaani|taara|kpop", "Asian/Pacific Islander"),
    (r"american indian", "Native American"),
    (r"turkish|mediterranean|ukrainian|russian|slavic|french", "International"),
]


def generate_tags(name, category):
    interest_tags = list(CATEGORY_INTEREST_TAGS.get(category, []))
    hobby_tags = []
    for pattern, tags in NAME_HOBBY_TAGS:
        if re.search(pattern, name, re.IGNORECASE):
            hobby_tags += [tag for tag in tags if tag not in hobby_tags + interest_tags]

    culture_tag = next(
        (tag for pattern, tag in NAME_CULTURE_TAGS if re.search(pattern, name, re.IGNORECASE)),
        None,
    )
    return interest_tags, hobby_tags, culture_tag


# Upsert on id so rerunning this script never duplicates rows. Contact and
# meeting time are not overwritten, a culture tag only fills an empty one, and
# an Instagram username is only replaced when orgmap.json has one, so values
# filled in by hand are kept.
INSERT_ORGS = """
INSERT INTO orgs (id, name, category, interest_tags, hobby_tags, culture_tag, contact, meeting_time, instagram_username)
VALUES %s
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    interest_tags = EXCLUDED.interest_tags,
    hobby_tags = EXCLUDED.hobby_tags,
    culture_tag = COALESCE(orgs.culture_tag, EXCLUDED.culture_tag),
    instagram_username = COALESCE(EXCLUDED.instagram_username, orgs.instagram_username)
"""

# Fields shared by backend/events.json and the events table.
EVENT_COLUMNS = [
    "id",
    "org_id",
    "title",
    "start_date",
    "end_date",
    "start_time",
    "end_time",
    "timezone",
    "location",
    "status",
    "details_complete",
    "source_username",
    "source_url",
    "source_posted_at",
]

# events.json is rebuilt from the Instagram scrape, so its values always win.
INSERT_EVENTS = f"""
INSERT INTO events ({', '.join(EVENT_COLUMNS)})
VALUES %s
ON CONFLICT (id) DO UPDATE SET
    {', '.join(f'{column} = EXCLUDED.{column}' for column in EVENT_COLUMNS[1:])}
"""


def seed_database():
    usernames_by_org = {
        org_id: username for username, org_id in instagram_usernames.items()
    }

    # Turn both organization lists into rows that match the orgs table columns.
    org_rows = [
        (
            org["id"],
            org["name"],
            org["category"],
            org.get("interestTags") or [],
            org.get("hobbyTags") or [],
            org.get("cultureTag"),
            org.get("contact"),
            org.get("meetingTime"),
            usernames_by_org.get(org["id"]),
        )
        for org in tagged_orgs
    ]
    org_rows += [
        (org_id, name, category, *generate_tags(name, category), None, None, usernames_by_org.get(org_id))
        for org_id, name, category in CATALOG_ORGS
    ]

    event_rows = [
        tuple(event.get(column) for column in EVENT_COLUMNS) for event in events
    ]

    # Send each table's rows in a few large statements instead of one per row.
    # Orgs go first so every event's org_id already exists.
    with closing(get_connection()) as conn:
        with conn, conn.cursor() as cursor:
            execute_values(cursor, INSERT_ORGS, org_rows)
            execute_values(cursor, INSERT_EVENTS, event_rows)

    print(
        f"Seeding complete: {len(org_rows)} orgs ({len(tagged_orgs)} from "
        f"backend/org.json, {len(CATALOG_ORGS)} from the catalog) and "
        f"{len(event_rows)} events from backend/events.json."
    )


if __name__ == "__main__":
    seed_database()
